const quickWords = [
    "Si", "No", "Eros", "Io", "Ciao", "Per favore", "Posso andare",
    "Notizia", "Novità", "Oggi", "Domani", "Ai servizi?", "Mi puoi fare un favore?", "Mi passi", "Ho bisogno", "Ti manco?", "Ti sono mancato?", "Mi sei mancata!",
    "Ti chiedo scusa", "Primavera", "Estate", "Autunno", "Inverno",
    "Minuto", "Ora", "Giorno", "Settimana",
    "Lunedí", "Martedí", "Mecoledí", "Giovedí",
    "Venerdí", "Sabato", "Domenica", "Gennaio", "Febbraio",
    "Marzo", "Aprile", "Maggio", "Giugno", "Luglio", "Agosto",
    "Settembre", "Ottobre", "Novembre", "Dicembre", "Mi manchi!",
    "Ho una notizia", "Sbagliato",
    "Giusto", "G. L. I.", "A.N.F.A.S.", "Forse", "Scusa", "Pace",
    "Sciopero", "Scherzo", "Carrozzina", "Pullman", "Pulmino",
    "Mare", "Montagna", "Colazione", "Pranzo", "Cena", "Merenda",
    "Dove?", "Come?", "Quando?", "Perché?", "Grazie", "Prego",
    "Domanda", "Risposta", "Salutate", "Ti aspetto", "Ti presento",
    "Viene ...", "Volontario", "Volontaria", "Indovina ...", "Nebbia", "Pioggia",
    "Vento", "Sole", "Già", "Vigilia", "Edicola",
    "Quadrifogli", "O.F.T.A.L.", "A.I.A.S.", "Weekend",
    "Giornale", "Toast", "Ferie", "Mi raccomando",
    "Bello", "Brutto", "Caldo", "Freddo", "Triste", "Allegro",
    "Appuntamento", "Alto", "Basso", "Magro", "Grasso", "Aperto",
    "Chiuso", "Cattivo", "Buono", "Nuovo", "Vecchio", "Giovane",
    "Mario", "Dormendo", "Borraccia", "Gentile", "Odioso", "Dolce",
    "Difficile", "Facile", "Piccolo", "Grande", "Inizio",
    "Inizia", "Inizi", "Pulito", "Sporco", "Forte", "Debole",
    "Ricco", "Povero", "Continua", "Caffè", "Francesca", "Amicizia",
    "Simpatico", "Antipatico", "Stanco", "Ammalato", "Importante",
    "Finalmente", "Offro", "Arrabbiato", "Arrabbiata", "Segreti",
    "Asparagi", "Tè caldo", "Tè Freddo",
    "Cappuccino", "Shakerato", "Pavesini", "Chiara",
    "Colori", "Bianco", "Nero", "Arancione", "Azzurro", "Blu",
    "Grigio", "Marrone", "Rosso", "Rosa", "Verde", "Giallo",
    "Viola", "Turchese", "Bordeaux", "Minuti", "Secondi",
    "Rispetto", "Elisabetta", "Schiscetta",
    "Potrei avere il menù per favore?", "Posso sedermi vicino a te?",
    "Che dolci avete?", "Mi piacciono tutti i dolci",
    "Portatemi il conto", "Pizza", "Antipasto", "Pasta al ragù",
    "Pasta al forno", "Risotto", "Kisotto ai funghi porcini", "Carne",
    "Pollo", "Pesce", "Fritto", "Arrosto", "Hamburger di tacchino con rosmarino",
    "Hamburger di bovino", "Hamburger al formaggio", "Sofficini formaggio e mazzarella",
    "Patatine fritte", "Insalata", "Formaggio", "Wurstel",
    "Salame piccante", "Funghi", "Focaccia", "Tonno",
    "Gorgonzola", "Rucola", "Melanzane", "Zucchine", "Peperoni",
    "Polenta", "Cetriolini", "Frutta", "Tiramisù",
    "Gelato", "Amaretti", "Insalata russa", "Maionese", "Formaggio piattone",
    "Sottilette", "Mozzarella", "Vino",
    "Naturale", "Gassata", "CocaCola", "LemonSoda",
    "Estathè al limone", "Estathè alla pesca", "Limonata",
    "Limoncello", "Vodka", "Spumante",
    "Spritz", "Sorbetto", "Forchetta", "Coltello", "Cucchiaio", "Cucchiaino piatto",
    "Tovagliolo", "Pasta alla carbonara", "Vorrei bere",
    "Aperitivo", "The", "Birra", "Aranciata", "Acqua minerale",
    "Amaro", "Cosa posso offrirti?",
    "Quanto spendo?", "Posso avere un altro cucchiaino?", "Posso avere un tovagliolino?",
    "Cocktail", "Alcolico", "Latte", "Cioccolata",
    "Whisky", "Analcolico", "Chinotto",
    "Grappa", "Bicchiere", "Cous Cous", "Menta", "Lattina",
    "Mela", "Pera", "Arancia", "Pesca", "Uva", "Ciliegia", "Anguria",
    "Fragola", "Mora", "Mirtilli", "Banana", "Albicocca", "Fico",
    "Prugna", "Kiwi", "Mandarancio", "Melone", "Ananas", "Mandarino",
    "Susina", "Noci", "Prugne", "La frutta secca", "Nocciole",
    "Arachidi", "Mandorle", "Pistacchi", "Fichi secchi", "Tagliare",
    "Sbucciare", "Macedonia di frutta", "Aprire", "Schiacciare",
    "Frullato di frutta", "Abitare", "Abitazione", "Io abito", "Io abitavo",
    "Casa", "Palazzo", "Villa", "Condominio", "Scale", "Ascensore",
    "Solaio", "Cantina", "Porta finestra", "Balcone", "Giardino",
    "Ingresso", "Porta-abiti", "Porta-ombrelli", "Soggiorno", "Poltrone",
    "Divano", "Cucina", "Tavolo", "Sedie", "Frigorifero", "Lavastoviglie",
    "Lavello", "Forno", "Sala da pranzo", "Tinello", "Camera da letto",
    "Armadio", "Cassettone", "Letto", "Studio", "Scrivania", "Libreria",
    "Ripostiglio", "Scaffali", "Servizi", "Bagno", "Doccia", "Bidet",
    "Saponetta", "Asciugamano", "Spazzolino da denti", "Dentifricio",
    "Pettine", "Asciugacapelli", "Risotto zafferano e porcini", "Cotechino con lenticchie",
    "Cappone ripieno", "Filetto platessa", "Vitello tonnato", "Minestra di orzo",
    "Minestri", "Minestra", "Mistrone", "Broccole", "Cavolfiore", "Le cozze",
    "Dispiaciuta", "Dispiaciuto", "Spigatto", "Alla facciazza", "Non resisto più",
    "Bugiarda", "Scherza", "Scherzavo", "Bugiardo", "Scherzi", "Scherzava",
    "Bugiardi", "Buon divertimento", "Ti diverti ?", "Ti sei divertita ?",
    "Mi sono divertito", "Ci vediamo", "Facciamo la pace", "Benvenuto",
    "Tranquillo", "Ubriaco", "Benvenuta", "Tranquilla", "Ubriaca",
    "Benvenuti", "Fidanzato", "Compagno", "Obiettori", "Obiettore",
    "Me li dai", "Te li do", "Il diritto", "Fidanzata", "Compagna",
    "Compagnia", "Capodanno", "Epifania", "Beata Vergine Maria di Lourdes",
    "San Valentino", "Carnevale", "Pasqua", "Festa della Liberazione",
    "Festa dei Lavoratori", "Festa della Repubblica", "Ferragosto",
    "Assunzione della Beata Vergine", "Festa di Tutti i Santi",
    "Commemorazione dei Defunti", "Festa della Vittoria", "Immacolata Concezione",
    "Santo Natale", "Santo Stefano", "Auguri", "Buon Anno", "Onomastico",
    "Battesimo", "Matrimonio", "Tanti auguri", "Buona Pasqua", "Compleanno",
    "Cresima", "Congratulazioni", "Buon Natale", "Anniversario",
    "Prima Comunione", "Vacanze", "Lourdes", "Pellegrinaggio", "Oropa",
    "Chiesa", "Quaresima", "Funerale", "Cimitero", "Condoglianze", "Collo", "Schiena", "Spalla",
    "Il", "Lo", "L'", "La", "I", "Gli", "Le", "Un", "Uno", "Una", "Dei", "Degli", "Delle", "Dello", "Dell'",
    "Essere", "Avere", "Fare", "Dire", "Andare", "Venire", "Potere", "Dovere", "Volere", "Vedere", "Sentire",
    "Parlare", "Prendere", "Mettere", "Sapere", "Credere", "Lavorare", "Studiare", "Giocare", "Continuare",
    "Uscire", "Entrare", "Ritornare", "Mangiare", "Bere", "Dormire", "Ascoltare", "Guardare", "Capire",
    "Rispondere", "Scrivere", "Leggere", "Correre", "Nuotare", "Viaggiare", "Aspettare", "Cercare", "Trovare", "Iniziare",
    "Finire", "Pagare", "Pensare", "Sperare", "Chiedere", "Conoscere", "Amare", "Odio", "Stai",
    "Che", "Non", "Ma", "Come", "Lui", "Lei",
    "Noi", "Voi", "Loro", "Quando", "Dove", "Qui", "Cosa", "Chi", "Quale", "Quanto", "Ancora", "Poi", "Dopo", "Ieri",
    "Sempre", "Mai", "Tutto", "Nulla", "Altro", "Molto", "Poco", "Bene", "Male", "Tu", "Anche",
    "Da", "Di", "In", "Con", "Su", "Per", "Tra", "Fra", "Chiamo", "Sono", "Ho"
];